### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by Caziopei** [ignaciop000/binance-traderBot#19]
Hi, im having issues starting the bot. Not sure what i have missed, is there any dependencies i've missed out?

Using a Raspberry Pi 3 model B

This is what i do when i start bot.

> pi@Hercules:~/binance-traderBot $ sudo npm start
> 
> > binance-traderBot@1.0.0 start /home/pi/binance-traderBot
> > node ./trader
> 
> /home/pi/binance-traderBot/trader.js:14
> const { BinanceWS } = require('./binanceapi');
>       ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:134:18)
>     at node.js:962:3
> 
> npm ERR! Linux 4.14.69-v7+
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v4.3.2
> npm ERR! npm  v2.14.12
> npm ERR! code ELIFECYCLE
> npm ERR! binance-traderBot@1.0.0 start: `node ./trader`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the binance-traderBot@1.0.0 start script 'node ./trader'.
> npm ERR! This is most likely a problem with the binance-traderBot package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./trader
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls binance-traderBot
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/pi/binance-traderBot/npm-debug.log
> pi@Hercules:~/binance-traderBot $

[npm-debug.log](https://github.com/ignaciop000/binance-traderBot/files/2372345/npm-debug.log)

**Comment by ghost** [comment]
im also having the same problem any help please
