### ISSUE TITLE
Getting Closer but new issue

### ISSUE THREAD

**Issue by BatmanPDX** [ignaciop000/binance-traderBot#3]
The bot does what the other versions of yasinkuyu/binance-trader does, and stalls on this: 

Express server listening on port 3001
Started...
Trading Symbol: XVGBTC
Buy Quantity: 205.00000000
Stop-Loss Amount: 0
Profit Mode Options:
        Preferred Profit: 1.50%
        Buy Price : (Bid+ --increasing 0.00000001)
        Sell Price: (Ask- --decreasing 0.00000001)

____________________________________________________________________________

And then it eventually seems to start working, but then starts to create errors:

____________________________________________________________________________

XVGBTC : Buy order created id:38833374, quantity:205.00000000, buyPrice:0.00000534, Take profit aprox :0.00000550
Profit loss, called order, 38833374
Buy order fail (Not filled) Cancel order...
XVGBTC : Buy order created id:38833570, quantity:205.00000000, buyPrice:0.00000533, Take profit aprox :0.00000549
get_order Exception: Error: Request failed with status code 400
Profit loss, called order, 38833570
Buy order fail (Not filled) Cancel order...
XVGBTC : Buy order created id:38833579, quantity:205.00000000, buyPrice:0.00000534, Take profit aprox :0.00000550
get_order Exception: Error: Request failed with status code 400
get_order Exception: Error: Request failed with status code 400
(node:8932) UnhandledPromiseRejectionWarning: ReferenceError: None is not defined
    at Trading.cancel (C:\binance-traderbot\trading.js:498:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:8932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ignaciop000** [comment]
Do you have the last version?

**Comment by BatmanPDX** [comment]
does git fetch downloaded the latest changes or do I need to do something else. sorry new to using npm and git

**Comment by BatmanPDX** [comment]
Correction, it doesn't stall for as long as before, but I'm testing something with the stop-loss, it seems to be canceling as soon as a buy order is made.

**Comment by ignaciop000** [comment]
I added more logs and debug, To activate set debug:true 1 at coins.js for any coin

**Comment by mistersms** [comment]
hello,
i have added the debug line in coins.js, but there is no advanced logging visible.

here is my coins.js:

const coins = [
{
        symbol:'PPTBTC',
        quantity:2,
        stop_loss:10,
        mode:'profit',
        profit:0.9,
        increasing:0.0000001,
        decreasing:0.0000001,
        loop:0,
        wait_time:0.7,
        debug: true,
}
]

module.exports = coins;


i have running the newest 
[trading.js.txt](https://github.com/ignaciop000/binance-traderBot/files/2070958/trading.js.txt)
and
[binance_rest.js.txt](https://github.com/ignaciop000/binance-traderBot/files/2070961/binance_rest.js.txt)
with debugging options.

should i see the advanced logging on the console?

thx
