### ISSUE TITLE
Error: unexpected server response (504)

### ISSUE THREAD

**Issue by dreKion** [ignaciop000/binance-traderBot#8]
`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (504)
    at ClientRequest._req.on (/home/drekion/Documentos/new/binance-traderBot-master/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
`

Can you control 504 error?  Thanks

**Comment by JimboFromLimbo** [comment]
`Npm install` should fix it?  if not check that your keys are correct
